### ISSUE TITLE
node_preamble package?

### ISSUE THREAD

**Issue by mbullington** [pulyaevskiy/node-interop#1]
Hello! I'm the creator of the [node_preamble](https://github.com/mbullington/node_preamble.dart) package, the preamble you're using in both tool/ and in the transformer for using Dart code on Node.js.

Just curious, why can't you use the node_preamble package that's on pub? Is there something with the preamble API we can change to make using the package more viable for node-interop?

If that's not possible, I'd still like to ask you to add the LICENSE from node_preamble somewhere to your repository, crediting both myself and the Dart team who made the preamble possible.

https://github.com/mbullington/node_preamble.dart/blob/master/LICENSE

I'm looking through your codebase right now, and look forward to potentially contributing in the future. Thanks!

**Comment by pulyaevskiy** [comment]
Hi, this is definitely something I was going to change. I had to extract it temporarily because of two reasons: I was doing lots of experimentation and I ended up adding a couple things to it, and I didn't know how to include resources from other packages yet.

I'd definitely prefer to use the node_preamble package itself though.

As for the API, what I discovered is that the preamble need to export all the Node globals to 'self', you can see I added __dirname and __filename.

There is also a question of how to make it a bit more customizable. For instance, adding more globals for Atom extensions.

I can create related issues in your repo on github to address these. For I'd only need the node globals updated, so when it merged I can update this repo to uses the node_preamble package directly.

Would this work for you?

This node_interop package is still in a very experimental phase so requires some cleanup.

**Comment by mbullington** [comment]
So I was able to add the suggested improvements to node_preamble's 0.4.0 release. Could you please check out this commit and see if it provides everything you need?

https://github.com/mbullington/node_preamble.dart/commit/ee486ed7c294ec2cb06a1855a327baa86df0a3c4

I'm not entirely sure how Atom globals work, so I'm not sure if the added API is too simple for your use-case or not. If it doesn't work, it wouldn't be too difficult to just concat more JavaScript code to the end of the preamble in your transformer.

Thanks!

**Comment by pulyaevskiy** [comment]
Thanks a lot for the update! I've just published `0.0.2` where I switched to using node_preamble. 

I think the new API for registering globals should be enough, but I need to do more tests.

Closing this issue, but feel free to re-open if I missed anything!
