### ISSUE TITLE
Unsupported operation: Platform._version in node_http post

### ISSUE THREAD

**Issue by lukef** [pulyaevskiy/node-interop#19]
When doing a `http.post` I get the following error:

```
Unsupported operation: Platform._version
```

`http.get` works fine. I will try to do a minimal use case but based on my tests it happens every time.

For context, this is after running dart2js and is being executed within the context of a firebase function. I also get the same error when I just try to use the dart/http package (as opposed to node_http) as well. Not sure if it is related to dart2js.

**Comment by pulyaevskiy** [comment]
Thanks for reporting!

Could you also provide version of Dart SDK you used to compile your code?

**Comment by pulyaevskiy** [comment]
Found this issue which seems related: https://github.com/dart-lang/http/issues/149

Oh, I think I know why it fails, not sure yet why it doesn't in tests though.
We currently export everything declared in `package:http` including top level functions, which is wrong and needs to be changed.

Will work on a fix tomorrow. In the meantime a workaround that _should_ work is to instantiate a `NodeClient` and use that instance to send requests instead of library-level methods.

**Comment by lukef** [comment]
Using: `Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "windows_x64"`

As an addition, the following code works:

```dart
final client = new http.NodeClient();
final response = await client.post(url, body: data);
```

**Comment by lukef** [comment]
Looks like we commented at the same time :) The workaround works but i'll try out the fix when it hits! Thanks for following up so quickly.

**Comment by pulyaevskiy** [comment]
Yeah :) Thanks for your help. Will update here when I have something.

**Comment by pulyaevskiy** [comment]
@lukef  FYI: https://pub.dartlang.org/packages/node_http/versions/1.0.0-dev.4.0 should fix this issue.

**Comment by lukef** [comment]
Let me give it a test!

**Comment by pulyaevskiy** [comment]
How did it go? :)

**Comment by lukef** [comment]
Sorry for the delay. It works! I re-verified that the bug existed before upgrading. After upgrading the issue is gone.

Thanks again for following up so quickly!

**Comment by pulyaevskiy** [comment]
Awesome, thanks for checking it!
