### ISSUE TITLE
Version solving failed.

### ISSUE THREAD

**Issue by asaarnak** [pulyaevskiy/node-interop#42]
When my project depends on both build_runner ^0.10.0 and build_node_compilers ^0.1.10, version solving failed.

Because build_runner >=0.10.0 depends on build_runner_core >=0.3.0 <0.3.1 which depends on json_annotation ^1.0.0

**Comment by pulyaevskiy** [comment]
Thanks for reporting! Looks like I'll need to bump version constraints. Will take a look asap.

**Comment by grundid** [comment]
I have a similar problem due to an update to Dart 2.0.0

Because build_node_compilers <0.1.9 requires SDK version >=2.0.0-dev <2.0.0 and build_node_compilers >=0.1.9 depends on
  build_modules ^0.2.2+1, every version of build_node_compilers requires build_modules ^0.2.2+1.
So, because build_modules >=0.1.0+1 <0.3.0 requires SDK version >=1.22.1 <2.0.0 or >=2.0.0-dev.48 <2.0.0 and  myproject_functions depends on build_node_compilers ^0.1.0, version solving failed.

**Comment by pulyaevskiy** [comment]
I've just published 0.1.11 of build_node_compilers which should address this issue.

**Comment by asaarnak** [comment]
Thanks, looks good now!
