### ISSUE TITLE
Provide access to stderr in node_io

### ISSUE THREAD

**Issue by nex3** [pulyaevskiy/node-interop#70]
node_io doesn't currently support `dart:io`'s `stderr` field, which makes it difficult to use it to write command-line apps.

**Comment by pulyaevskiy** [comment]
Thanks for submitting. I looked briefly last night to estimate the scope. Should be able to cover this and #69 over the weekend.

**Comment by pulyaevskiy** [comment]
node_io 1.1.1 adds `stdout` and `stderr` library-level properties.
No `stdin` yet, as there is no straightforward API in built-in Node.js modules to implement `readLineSync` and `readByteSync`. So more work is needed there, but [seems possible](https://github.com/anseki/readline-sync).

Closing this issue since `stderr` is now there.
