### ISSUE TITLE
build_node_compilers wont work with any packages that require analyzer > 0.39.0 which is a lot of them.

### ISSUE THREAD

**Issue by dannnnthemannnn** [pulyaevskiy/node-interop#82]
Can we update it?

**Comment by pulyaevskiy** [comment]
Will take a look tonight or over the weekend.

Thanks for reporting!

**Comment by lexaknyazev** [comment]
As the official `build*` packages now require analyzer `^0.40`, node compilers are incompatible with them.

@pulyaevskiy, would you be able to look into that?

**Comment by pulyaevskiy** [comment]
Sorry for the delay here. I just pushed a new version of build_node_compilers, `0.3.0` which allows to use a more recent version of build and build_runner. Note that it will not work with the latest versions of those packages because they are now relying on Dart SDK 2.10.x dev builds.

I added upgrade details in the changelog, but in short:

```yaml
dev_dependencies:
  build_runner: ">=1.10.0 <1.10.2"
  build_node_compilers: ^0.3.0
```

This is what seems to be working today.
